name: Get bing pictures

on:
  schedule:
    - cron: '0 13 * * ?' # 北京时间每天上午5点
  workflow_dispatch: # 允许手动触发

jobs:
  play:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
          
      - uses: actions/setup-node@v2
        with:
          node-version: 16
          cache: 'yarn'

      - name: Install and Build 🔧
        run: |
          yarn
          yarn build

      - name: Commit files 🐱‍🏍
        run: |
          git config --local user.email "1203123788@qq.com"
          git config --local user.name "zxyong"
          git pull
          git add ./
          git commit -m "update wallpaper"
          git push
